(()=>{
const {React:R,ReactNative:N,FluxDispatcher:D}=vendetta.metro.common;
const S=vendetta.plugin.storage, find=vendetta.metro.findByProps;
const users=find('getCurrentUser'), messages=find('getMessage','getMessages');
const h=R.createElement; let unpatch, stopped=true, queue=[], busy=false; const pending=new Set();
function account(){return users?.getCurrentUser?.()?.id||'unknown';}
function key(id){return 'msg:'+account()+':'+id;}
function native(){for(const name of ['NativeFileModule','RTNFileManager','DCDFileManager']){try{const m=globalThis.__turboModuleProxy?.(name)||globalThis.nativeModuleProxy?.[name]||N.NativeModules?.[name];if(m?.writeFile)return m;}catch{}}throw Error('파일 저장 모듈을 찾지 못했습니다');}
function config(){return S.config||{maxMB:50,totalMB:1024,enabled:true};}
function ids(){return S['ids:'+account()]||[];}
function save(m){S[key(m.id)]=m; const list=ids();if(!list.includes(m.id))S['ids:'+account()]=[m.id,...list];}
function base64(buf){const a=new Uint8Array(buf), chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';let out=[];for(let i=0;i<a.length;i+=3){const b=a[i+1],c=a[i+2],v=(a[i]<<16)|((b||0)<<8)|(c||0);out.push(chars[v>>>18],chars[(v>>>12)&63],b===undefined?'=':chars[(v>>>6)&63],c===undefined?'=':chars[v&63]);}return out.join('');}
function snapshot(m){return JSON.parse(JSON.stringify({id:m.id,channel_id:m.channel_id,content:m.content||'',author:m.author,timestamp:m.timestamp,attachments:m.attachments||[],embeds:m.embeds||[],edited_timestamp:m.edited_timestamp}));}
function capture(raw){if(!raw?.id||!raw.channel_id)return;const old=S[key(raw.id)];const m=snapshot({...old,...raw});m.history=old?.history||[];m.deleted=old?.deleted||false;m.media=old?.media||{};if(old&&raw.content!==undefined&&old.content!==raw.content)m.history=[...m.history,{content:old.content,at:raw.edited_timestamp||new Date().toISOString()}];save(m);for(const a of m.attachments){if(!m.media[a.id]?.uri&&!pending.has(account()+':'+m.id+':'+a.id)){pending.add(account()+':'+m.id+':'+a.id);queue.push({id:m.id,a,owner:account()});}}drain();}
async function drain(){if(busy||stopped)return;busy=true;try{while(queue.length&&!stopped){const j=queue.shift();if(j.owner!==account()){pending.delete(j.owner+':'+j.id+':'+j.a.id);continue;}const k=key(j.id),m=S[k];if(!m)continue;const cfg=config();let item;try{if(!/^https:\/\/(cdn|media)\.discordapp\.(com|net)\//.test(j.a.url))throw Error('지원하지 않는 첨부 주소');if(j.a.size>cfg.maxMB*1048576)throw Error('개별 용량 제한');const used=S['bytes:'+j.owner]||0;if(used+(j.a.size||0)>cfg.totalMB*1048576)throw Error('전체 용량 제한');const response=await fetch(j.a.url);if(!response.ok)throw Error('다운로드 HTTP '+response.status);const declared=Number(response.headers?.get?.('content-length')||0);if(declared>cfg.maxMB*1048576)throw Error('개별 용량 제한');const buf=await response.arrayBuffer();if(buf.byteLength>cfg.maxMB*1048576||used+buf.byteLength>cfg.totalMB*1048576)throw Error('용량 제한');const f=native(),path='persistent-logger/'+j.owner+'/'+j.id+'_'+String(j.a.id).replace(/[^0-9]/g,'')+'_'+String(j.a.filename||'attachment').replace(/[^a-zA-Z0-9._-]/g,'_');await f.writeFile('documents',path,base64(buf),'base64');const root=f.getConstants().DocumentsDirPath;item={uri:'file://'+root+'/'+path,path,bytes:buf.byteLength,type:j.a.content_type||'',name:j.a.filename};S['bytes:'+j.owner]=used+buf.byteLength;}catch(e){item={error:String(e.message||e)};}const current=S[k];pending.delete(j.owner+':'+j.id+':'+j.a.id);if(current)S[k]={...current,media:{...current.media,[j.a.id]:item}};}}finally{busy=false;}}
function event(e){if(stopped||!config().enabled||account()==='unknown')return;try{switch(e.type){case 'MESSAGE_CREATE':case 'MESSAGE_UPDATE':{const m=e.message;if(m){const cached=messages?.getMessage?.(m.channel_id,m.id);capture({...cached,...m});}break;}case 'LOAD_MESSAGES_SUCCESS':for(const m of e.messages||[])capture(m);break;case 'MESSAGE_DELETE':case 'MESSAGE_DELETE_BULK':for(const id of e.ids||[e.id]){const m=S[key(id)]||messages?.getMessage?.(e.channelId||e.channel_id,id);if(m){capture(m);const stored=S[key(id)];save({...stored,deleted:true,deletedAt:new Date().toISOString()});}}break;}}catch(e){vendetta.logger.error('Logger event',e);}}
const style={padding:12,color:'#eee'},button={padding:12,backgroundColor:'#39435c',margin:4,borderRadius:8};
function Settings(){vendetta.storage.useProxy(S);const [q,Q]=R.useState(''),[only,O]=R.useState(false),[page,P]=R.useState(0);const cfg=config();const all=ids().map(id=>S[key(id)]).filter(Boolean).filter(m=>(!only||m.deleted)&&(!q||[m.content,m.author?.username,m.channel_id,...m.history.map(x=>x.content)].join(' ').toLowerCase().includes(q.toLowerCase())));function btn(label,fn){return h(N.Pressable,{style:button,onPress:fn},h(N.Text,{style:{color:'white'}},label));}
return h(N.ScrollView,{style:{backgroundColor:'#17181c'},contentContainerStyle:{paddingBottom:50}},h(N.Text,{style},'Persistent Logger · 모든 수신 채널/DM\n기록 '+ids().length+'개 · 첨부 '+Math.round((S['bytes:'+account()]||0)/1048576)+'MB\n앱이 수신하거나 불러온 메시지만 저장됩니다.'),btn(cfg.enabled?'기록 켜짐 — 누르면 일시정지':'기록 일시정지 — 누르면 시작',()=>S.config={...cfg,enabled:!cfg.enabled}),h(N.Text,{style},'개별 첨부 제한(MB)'),h(N.TextInput,{style,keyboardType:'numeric',defaultValue:String(cfg.maxMB),onEndEditing:e=>{const n=Number(e.nativeEvent.text);if(n>0)S.config={...config(),maxMB:n};}}),h(N.Text,{style},'총 첨부 제한(MB)'),h(N.TextInput,{style,keyboardType:'numeric',defaultValue:String(cfg.totalMB),onEndEditing:e=>{const n=Number(e.nativeEvent.text);if(n>0)S.config={...config(),totalMB:n};}}),h(N.TextInput,{style:{...style,backgroundColor:'#292b33'},placeholder:'내용 / 작성자 / 채널 ID 검색',placeholderTextColor:'#aaa',value:q,onChangeText:x=>{Q(x);P(0);}}),btn(only?'삭제된 기록만':'모든 기록',()=>{O(!only);P(0);}),...all.slice(page*30,page*30+30).map(m=>h(N.View,{key:m.id,style:{padding:12,margin:6,backgroundColor:'#242630',borderRadius:8}},h(N.Text,{style:{color:m.deleted?'#ff8c8c':'#ddd'}},(m.deleted?'[삭제됨] ':'')+(m.author?.username||'알 수 없음')+' · '+m.timestamp+'\n채널 '+m.channel_id),h(N.Text,{selectable:true,style},m.content||'(텍스트 없음)'),...m.history.map((x,i)=>h(N.Text,{key:'h'+i,selectable:true,style:{color:'#efbf75'}},'수정 전: '+x.content)),...m.attachments.map(a=>{const f=m.media[a.id];return h(N.View,{key:a.id},h(N.Text,{style},a.filename+(f?.error?' · 저장 실패: '+f.error:!f?.uri?' · 다운로드 대기':'')),f?.uri&&((a.content_type||'').startsWith('image/')||/\.(png|jpg|jpeg|gif|webp)$/i.test(a.filename))?h(N.Image,{source:{uri:f.uri},style:{height:200,width:'100%'},resizeMode:'contain'}):null,f?.uri?btn('파일 열기 / 공유',()=>N.Share.share({url:f.uri,title:a.filename,message:f.uri}).catch(e=>N.Alert.alert('파일 열기 실패',String(e)))):null);}),btn('텍스트 복사',()=>vendetta.metro.common.clipboard.setString(JSON.stringify(m,null,2))))),h(N.Text,{style},'검색 결과 '+all.length+'개 · 페이지 '+(page+1)),btn('이전',()=>P(Math.max(0,page-1))),btn('다음',()=>P(Math.min(Math.max(0,Math.ceil(all.length/30)-1),page+1))),btn('현재 계정 기록/첨부 삭제',()=>N.Alert.alert('기록 삭제','저장된 메시지와 첨부파일을 삭제할까요?',[{text:'취소',style:'cancel'},{text:'삭제',style:'destructive',onPress:async()=>{if(busy){N.Alert.alert('잠시 기다려줘','다운로드 완료 후 기록을 일시정지하고 다시 삭제해줘.');return;}queue=[];for(const id of ids()){const m=S[key(id)];for(const f of Object.values(m?.media||{})){if(f.path)try{await native().removeFile('documents',f.path);}catch{}}delete S[key(id)];}S['ids:'+account()]=[];S['bytes:'+account()]=0;}}])));}
return {onLoad(){if(!D?.dispatch)throw Error('FluxDispatcher unavailable');stopped=false;unpatch=vendetta.patcher.instead('dispatch',D,(args,original)=>{const e=args[0];event(e);if(!config().enabled||account()==='unknown')return original(...args);
if(e.type==='MESSAGE_DELETE'||e.type==='MESSAGE_DELETE_BULK'){
const known=(e.ids||[e.id]).filter(id=>S[key(id)]?.deleted);
for(const id of known){const m=S[key(id)];original({type:'MESSAGE_UPDATE',message:{...m,content:'[삭제됨] '+m.content,attachments:m.attachments.map(a=>{const f=m.media[a.id];return f?.uri?{...a,url:f.uri,proxy_url:f.uri}:a;})}});}
if(e.type==='MESSAGE_DELETE'&&known.length)return;
if(e.type==='MESSAGE_DELETE_BULK'){const rest=e.ids.filter(id=>!known.includes(id));if(!rest.length)return;return original({...e,ids:rest});}
}
if(e.type==='LOAD_MESSAGES_SUCCESS'&&Array.isArray(e.messages)){
const channel=e.channelId||e.channel_id||e.messages[0]?.channel_id;
const list=e.messages.slice(),seen=new Set(list.map(m=>m.id));
for(const id of ids()){const m=S[key(id)];if(m?.deleted&&m.channel_id===channel&&!seen.has(id)){list.push({...m,content:'[삭제됨] '+m.content,attachments:m.attachments.map(a=>{const f=m.media[a.id];return f?.uri?{...a,url:f.uri,proxy_url:f.uri}:a;})});}}
list.sort((a,b)=>a.id.length!==b.id.length?b.id.length-a.id.length:b.id.localeCompare(a.id));return original({...e,messages:list});
}return original(...args);});for(const id of ids()){const m=S[key(id)];if(m&&!m.deleted)capture(m);}},onUnload(){stopped=true;queue=[];pending.clear();unpatch?.();},settings:Settings};
})()
